[target.'cfg(target_arch = "wasm32")']
# Use "wasmer" for running tests when compiled to WebAssembly
runner = ["wasmer", "run"]
# This is needed so the module is compiled with atomics support (shared memory)
# We add the `-no-check-features` linker args because otherwise one of the modules fails to link
rustflags = '-Ctarget-feature=+atomics,+bulk-memory -Clink-args=--no-check-features'

[unstable]
# We want to make sure std gets built with atomics, too
build-std = ['std', 'panic_abort']

