# Separate workflow for the wasmer-web crate.
#

name: Wasmer Web

on:
  push:
    branches:
      - main
  pull_request:

# Automatically cancel previous workflow runs when a new commit is pushed.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_NET_GIT_FETCH_WITH_CLI: "true"

jobs:
  web:
    name: Build and Test (wasmer-web)
    runs-on: ubuntu-latest
    defaults:
      run:
          working-directory: lib/wasi-web
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Rust Cache
      uses: Swatinem/rust-cache@v2

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: nightly-2023-05-25

    - name: Install wasm-pack
      uses: taiki-e/install-action@v2
      with:
        tool: wasm-pack

    - name: Setup Chromedriver
      uses: nanasess/setup-chromedriver@v2
      # Temporary workaround for https://github.com/nanasess/setup-chromedriver/issues/190
      with:
        chromedriver-version: '114.0.5735.90'

    - name: Show Rust version
      run: rustc --version --verbose

    - name: Check
      run: cargo check --verbose --locked

    - name: Browser Integration Tests
      run: |
        set -xe
        npm install
        npm run build
        npm run dev &
        NPM_PID=$!
        # Give the webpack dev server time to start
        sleep 10

        cd ../../tests/wasmer-web
        cargo test --verbose --locked -- --test-threads=1

  wasix:
    name: Build and Test (wasix)
    runs-on: ubuntu-latest
    defaults:
      run:
          working-directory: lib/wasix
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Rust Cache
      uses: Swatinem/rust-cache@v2

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: nightly-2023-05-25

    - name: Install wasm-pack
      uses: taiki-e/install-action@v2
      with:
        tool: wasm-pack

    - name: Show Rust version
      run: rustc --version --verbose

    - name: Check
      run: cargo check --verbose --locked --features=wasmer/js,wasmer/std,js --no-default-features

    - name: Integration Tests
      run: wasm-pack test --chrome --headless --features=wasmer/js,wasmer/std,js --no-default-features

  lints:
    name: Lints and Formatting
    runs-on: ubuntu-latest
    defaults:
      run:
          working-directory: lib/wasi-web
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Rust Cache
      uses: Swatinem/rust-cache@v2

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: nightly-2023-05-25

    - name: Check formatting
      shell: bash
      run: cargo fmt --check

    - name: Check clippy
      shell: bash
      run: cargo clippy -- -Dwarnings
